// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: 'TextBook', // This will automatically generate a sidebar from the 'TextBook' directory
    },
  ],
};

export default sidebars;